name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        env: # Or as an environment variable
           MAILJET_SECRET: ${{ secrets.MAILJET_SECRET }}
           MAILJET_API: ${{ secrets.MAILJET_API }}
           GIF: ${{ secrets.GIF }}        
           MY_EMAIL: ${{ vars.MY_EMAIL }}
        run: "deno task build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "paulanthony-forgiveme-47"
          entrypoint: "main.ts"
          root: "."
          
          
